name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        with:
          cache: true

      - name: Install
        run: pnpm install

      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: pnpx changelogithub
